services:
  test-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noovox
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  app:
    build: .
    ports:
      - "5000:5000"
    command: >
      bash -c "
        python app.py
      "

  test:
    build: .
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      MYSQL_HOST: test-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: noovox
    command: >
      bash -c "
        /app/scripts/wait-for test-db:3306 --timeout=60 && \
        
        echo $$MYSQL_HOST && \
        mysql -h $$MYSQL_HOST -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE < noovox/db_schema.sql &&
        pytest -s --capture=no
      "
